service:
  name: authenticated-hello-world

provider:
  name: cloudflare
  config:
    accountId: 9010f0cbdbd67971275d4fb1a05392c7
    zoneId: 2aed65c982e734610dbd68eedd3e072a

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    worker: hello
    script: dist/cloudflare-routes
    events:
      - http:
          url: matthewjleon.com/api/*
          method: ANY
